# Generated by Django 2.2 on 2021-03-01 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
        ),
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_name', models.CharField(max_length=30)),
                ('per_piece_price', models.PositiveSmallIntegerField()),
                ('per_box_pieces', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('Cup', 'Cup Type'), ('Cone', 'Cone Type'), ('Candy-Bar', 'Candy Bar Type'), ('Choco-Bar', 'Choco Bar Type')], max_length=15)),
                ('freezer', models.PositiveSmallIntegerField(choices=[(1, 'Freezer One'), (2, 'Freezer Two'), (3, 'Freezer Three')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_boxes', models.PositiveSmallIntegerField(default=0)),
                ('last_update', models.DateField(auto_now=True)),
                ('icecream', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stock_app.Icecream')),
            ],
            options={
                'verbose_name': 'Total Stock',
                'verbose_name_plural': 'Total Stocks',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_boxes', models.PositiveSmallIntegerField(default=0)),
                ('arrival_boxes', models.PositiveSmallIntegerField(default=0)),
                ('all_boxes', models.PositiveSmallIntegerField(default=0)),
                ('sold_boxes', models.PositiveSmallIntegerField(default=0)),
                ('remain_boxes', models.PositiveSmallIntegerField(default=0)),
                ('entry_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_app.Dates')),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_app.Total')),
            ],
        ),
    ]
