# Generated by Django 2.2 on 2021-03-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='freezer',
        ),
    ]
