# Generated by Django 2.2 on 2021-03-01 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_boxes', models.PositiveSmallIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_app.Dates')),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_app.Total')),
            ],
        ),
    ]
